- hosts: tag_Name_tf_instance_back_icesi_health
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: get info on backend container
      docker_container_info:
        name: appBack
      register: result

    - name: Does container exists?
      ansible.builtin.debug:
        msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

    - name: Stop container
      docker_container:
        name: appBack
        state: stopped
      when: result.exists

    - name: remove container
      docker_container:
        name: appBack
        state: absent

    - name: remove image
      docker_image:
        state: absent
        name: appBack

    - name: Execute docker container
      docker_container:
        name: appBack
        image: manuel11coral23/frontend:{{ tag }} #Cambiar imagen
        state: started
        pull: true
        published_ports:
          - "8000:8000"  #Puerto diferente a frontend. 
        env: 
          BACK_HOST: '{{ BD_host }}'